version: "3"

services:
  api:
    build: .
    image: somkiat/node-api
    ports:
      - 3000:3000
  db:
    image: mysql:8.0.29
    volumes:
      - ./mysql/data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=workshop
      - MYSQL_ROOT_PASSWORD=password